### ISSUE TITLE
macosx install fail

### ISSUE THREAD

**Issue by hp4k1h5** [FormidableLabs/victory-cli#5]
I followed the instructions several times first installing victory-cli locally in a project, and then installed librsvg through brew. This local install itself seemed to work, but it never recognized the victory-cli command, and i couldn't run this command in any of the obvious project directories. 
So then i uninstalled v-c and tried installing -globally, then exporting PATH and reinstalling several times. I ran the global installs with sudo, but still got some permission errors in the log.

I keep running into this eventually : npm ERR! Failed at the librsvg@0.7.0 install script.
There's a fair amount of debug info before that, which ill just paste below. If others have found a workaround, it would be much appreciated. In the meantime, maybe i'll just use the .js components directly. cheers. 

node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@9.2.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/lib/node_modules/victory-cli/node_modules/fsevents
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/victory-cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/victory-cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/victory-cli/node_modules/fsevents
node-pre-gyp ERR! node -v v9.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

> librsvg@0.7.0 install /usr/local/lib/node_modules/victory-cli/node_modules/librsvg
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/victory-cli/node_modules/librsvg/build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/victory-cli/node_modules/librsvg
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/victory-cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! librsvg@0.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the librsvg@0.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above

**Comment by ryan-roemer** [comment]
Can you show us what commands you're actually typing?

I'm expecting something like:

```
$ brew install librsvg
$ npm install -g victory-cli
```

Thanks!

**Comment by ryan-roemer** [comment]
Also how is your node installed? Are you using `nvm`?

One helpful thing is looking at:

```
$ which node
```

**Comment by hp4k1h5** [comment]
Hi Ryan,
i'll paste some history here: 
~~n ~n°<@ cat .zsh_history | grep victory
: 1510973040:0;npm install victory-cli
: 1511022850:0;ls **/*victory-cli*
: 1511022856:0;ls /**/*victory-cli*
: 1511022863:0;ls ./**/*victory-cli*
: 1511023190:0;npm uninstall victory-cli
: 1511023271:0;npm install -g victory-cli
: 1511023321:0;sudo npm install -g victory-cli
: 1511023371:0;which victory-cli
: 1511023476:0;sudo npm install -g victory-cli
: 1511212094:0;cat .zsh_history | grep victory

_____
~~n ~n°<@ cat ./.zsh_history | grep librsvg
: 1511022396:0;brew install librsvg
: 1511231749:0;cat ./.zsh_history | grep librsvg

i have node installed from their native installer 
/usr/local/bin/node
it works with other projects

**Comment by sgregson** [comment]
FWIW I had the same issue (failed to install on MacOS with node v8 via NVM) and resolved it by installing `librsvg` before attempting to `npm install -g victory-cli` instead of the order specified in the README. Is `librsvg` a dependency of the install, not just the execution of the lib?

Confirmed operational by `victory-cli -c line --print` afterwards.

**Comment by hp4k1h5** [comment]
thanks sgregson, this worked but i had to use 

sudo npm install --unsafe-perm -g victory-cli
